#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: "3.7"
services:
  splunk:
    build:
      context: .
      dockerfile: Dockerfile.splunk
      args:
        SPLUNK_VERSION: ${SPLUNK_VERSION}
    ports:
      - "8000"
      - "8088"
      - "8089"
      - "9997"
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
  sc4s: 
    build:
      context: ./sc4s
      dockerfile: Dockerfile.sc4s
    command: -det
    links:
      - splunk
    ports:
      - "6514"
      - "514"
      - "601"
      - "514/udp"
      - "5000-5050"
      - "5000-5050/udp"
    stdin_open: true
    tty: true
    environment:
      - SPLUNK_HEC_URL=https://splunk:8088
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SC4S_SOURCE_TLS_ENABLE=no
      - SC4S_DEST_SPLUNK_HEC_TLS_VERIFY=no
      - SC4S_ARCHIVE_GLOBAL=no
      - SC4S_SOURCE_STORE_RAWMSG=yes
      - SC4S_LISTEN_CHECKPOINT_SPLUNK_NOISE_CONTROL=yes
      - SC4S_SOURCE_LISTEN_UDP_SOCKETS=2

volumes:
  splunk-sc4s-var:
    external: false